"""Description of migration

Revision ID: 02205996e302
Revises: 42909378cca1
Create Date: 2023-07-21 11:04:32.823984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02205996e302'
down_revision = '42909378cca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_permissions')
    # ### end Alembic commands ###
