"""intial

Revision ID: 316c44e6d1b6
Revises: 95ec7a9134a3
Create Date: 2023-05-10 15:32:26.996989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316c44e6d1b6'
down_revision = '95ec7a9134a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.drop_constraint('user_order_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_order_category_id_fkey', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###
