"""intial

Revision ID: 790443203b76
Revises: 0cdc827ce7c5
Create Date: 2023-05-10 11:57:36.486135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790443203b76'
down_revision = '0cdc827ce7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.drop_constraint('user_order_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_order_category_id_fkey', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###
